site_name: Caitlyn's Codecakes Guidebook

pages:
    - Home: index.md
    - Lessons: 
      - 1. Image: lesson1.md
      - 2. Move: lesson02.md
      - 3. Control: lesson03.md
      - 4. Chase: lesson04.md
      - 5. Text: text.md
      - 6. Timer: timer.md
      - 7. Level: level.md
      - Answers: answers.md
    - Exercises:
      - for loops: exercises/for.md
      - lists: exercises/list.md
    - Projects:
      - Restaurant Finder Lesson: project/restaurant.md
      - Restaurant Finder Code: project/restaurantListProject.md
